### ISSUE TITLE
Warning: date(): It is not safe to rely on the system's timezone settings. 

### ISSUE THREAD

**Issue by Sevyls** [etobi/Typo3ExtensionUtils#13]
On OS X Yosemite on **$ t3xutils.phar extract file.t3x directory** I get the following warning:

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///...../Typo3ExtensionUtils/bin/t3xutils.phar/lib/etobi/extensionUtils/Controller/T3xController.php on line 100

````
$ php -v
PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
````

**Comment by dmitryd** [comment]
http://bit.ly/1HQJtVC ?

**Comment by Sevyls** [comment]
Sorry for bothering you.
