### ISSUE TITLE
Do I have to update the extension version manually?

### ISSUE THREAD

**Issue by cweiske** [etobi/Typo3ExtensionUtils#15]
The docs (README) do not make it clear who is in charge of updating the extension version in `ext_emconf.php`.

Does the tool does it automatically?

**Comment by etobi** [comment]
I always found confusing when the (old-old) extensionmanager wanted to raise the version in my ext_emconf.
So, the t3xutils does not modify your ext_emconf during upload to give the developer full control.
You have to increase the version yourself and then upload the extension to TER

**Comment by etobi** [comment]
#1f323a7939b6e8d6b559e4dbfd5007ae50f6f765
