### ISSUE TITLE
autoload information not transmitted on upload

### ISSUE THREAD

**Issue by oliverklee** [etobi/Typo3ExtensionUtils#16]
The PHPUnit typo3 extension contains autoload information in its ext_emconf.php: https://github.com/TYPO3-extensions/phpunit/blob/master/ext_emconf.php

If I read the code correctly, this information currently is not transmitted when I upload the extension to the TER using the upload command.

**Comment by oliverklee** [comment]
I've created a ticket for the phpunit extension in case we need to change something there as well: https://forge.typo3.org/issues/72146

**Comment by oliverklee** [comment]
I've created a ticket for the TER problem: https://forge.typo3.org/issues/72594

**Comment by etobi** [comment]
t3xutils does no longer exlude the ext_emconf.php, thus it will not be magically autogenerated anymore.

Thanks Henri Nathanson for the hint (https://forge.typo3.org/issues/72146).
