### ISSUE TITLE
Change 

### ISSUE THREAD

**Issue by bvbmedia** [etobi/Typo3ExtensionUtils#22]
When I upload the ZIP file of the extensions to TER manually it works fine, but when I use your tool it says "Maximum upload size exceeded".

Could you raise the maxUploadSize?

Change:
public static function getExtensionFilesData($path, $excludeForPackaging = '(CVS|\..*|.*~|.*\.bak)', $maxUploadSize = 31457280) {

To:
public static function getExtensionFilesData($path, $excludeForPackaging = '(CVS|\..*|.*~|.*\.bak)', $maxUploadSize = 51457280) {

**Comment by etobi** [comment]
i've made your suggested change in Helper.php. Could you please double-check and test if that is solving your issue?

**Comment by basvanbeeknl** [comment]
Hey Tobias that is fast. Let me test it directly. :+1:

**Comment by basvanbeeknl** [comment]
Plugin size is 38mb.

I have bad luck, new error:

[root@baslaplinux ter_1462459118]# /root/Typo3ExtensionUtils/bin/t3xutils.phar upload xxx xxx multishop "Converted manual to RsT" /root/ter_1462459118/multishop
You're using a different version then the latest available on github. Consider updating using the "selfupdate" command.
Visit https://github.com/etobi/Typo3ExtensionUtils for more information.

PHP Warning:  SoapClient::__doRequest(): SSL: Connection reset by peer in phar:///root/Typo3ExtensionUtils/bin/t3xutils.phar/lib/etobi/extensionUtils/ter/Soap.php on line 202
SOAP-Error: Failed Sending HTTP SOAP request

**Comment by basvanbeeknl** [comment]
Manually making ZIP and uploading that works though:

![image](https://cloud.githubusercontent.com/assets/3802035/15046934/a3e1bdbc-12e2-11e6-8ee1-f2bd297933b8.png)
